# This is a basic workflow to help you get started with Actions

name: practice

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  eumran:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 현재 레포지토리를 가져옴
      - uses: actions/checkout@v2
      - uses: actions/github-script@v3
        id: api
        with:
          github-token: ${{ secrets.AYA_GG_TOKEN }}
          script: |
            const data = await github.request('GET /repos/sdbx/aya.gg/contents/data/endpoints.json');

            console.log(data);

            return data;
          result-encoding: string
      - run: curl ${{ steps.api.outputs.result }} > endpoints.json
      - run: node .github/actions/eumran/index.js